apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "myservice.fullname" . }}

spec:
  maxUnavailable: {{ .Values.global.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "myservice.selectorLabels" . | nindent 6 }}