apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myservice.fullname" . }}
data:
    NODE_ENV: {{ .Values.global.NODE_ENV }}
    mode: {{ .Values.ENV_VARS.mode }}
    NER_ROUTE: {{ .Values.global.ner_ROUTE }}
    SENTIMENT_ROUTE: {{ .Values.global.sentiment_ROUTE }}