apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myservice.fullname" . }}
data:
    NODE_ENV: {{ .Values.global.NODE_ENV }}
    mode: {{ .Values.ENV_VARS.mode }}
    PORTAL_ROUTE: {{ .Values.global.PORTAL_ROUTE }}