global:
  namespace: merchantfs-development
  NODE_ENV: development
  MERCHANT_PORTAL_ROUTE: mercants.development.payformance.io
  STORYBOOK_ROUTE: storybook.development.payformance.io
  routeAnnotations:
    haproxy.router.openshift.io/balance: source
    haproxy.router.openshift.io/disable_cookies: "false"
    haproxy.router.openshift.io/timeout: 2m
  podAnnotations:
    reloader.stakater.com/auto: "true"
### Sub Charts Specific Values ###
# Merchant Portal   
merchant-portal:
  enabled: true
  image:
    tag: development-2c933cc2
  ENV_VARS:
    mode: "common"
# Storybook
storybook:
  enabled: true
  image:
    tag: development-63d20e46
  ENV_VARS:
    mode: "common"
