apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myservice.fullname" . }}
data:
    NODE_ENV: {{ .Values.global.NODE_ENV }}
    mode: {{ .Values.ENV_VARS.mode }}
    CHECKOUT_ROUTE: {{ .Values.global.CHECKOUT_ROUTE }}
    PAYMENT_ROUTE: {{ .Values.global.PAYMENT_ROUTE }}
